# SPDX-FileCopyrightText: 2025 facility13.devops contributors <https://github.com/ForNeVeR/facility13.devops>
#
# SPDX-License-Identifier: MIT

- import_playbook: emulsion.yml
- import_playbook: newsboat.org.certificate.yml
- import_playbook: newsboat.org.www.yml
