# SPDX-FileCopyrightText: 2025 facility13.devops contributors <https://github.com/ForNeVeR/facility13.devops>
#
# SPDX-License-Identifier: MIT

- name: Certificate renewal for newsboat.org
  hosts: newsboat_org
  become: true

  vars_files:
    - secrets.yml

  vars:
    gandi_config_path: /etc/letsencrypt/gandi.ini

  tasks:
    - name: Install the required packages
      ansible.builtin.apt:
        name: python3-certbot-dns-gandi
        state: present
        cache_valid_time: 3600
      notify: Run certbot # only required once, after installation, it will configure renewal during the run

    - name: Ensure the configuration file for gandi renewal exists
      ansible.builtin.template:
        src: gandi.ini.j2
        dest: '{{ gandi_config_path }}'
        owner: root
        group: root
        mode: u=rw,go=

  handlers:
    - name: Run certbot
      ansible.builtin.command: certbot certonly --authenticator dns-gandi --dns-gandi-credentials {{ gandi_config_path }} -d newsboat.org
      register: certbot
      changed_when: certbot.rc == 0
