# SPDX-FileCopyrightText: 2025 facility13.devops contributors <https://github.com/ForNeVeR/facility13.devops>
#
# SPDX-License-Identifier: MIT

---
collections:
  - name: community.docker
    version: 3.7.0
  - name: ansible.posix
    version: 1.5.4
